CREATE DATABASE IF NOT exists LOGIN;

CREATE TABLE IF NOT EXISTS 
LOGIN.LOGINDETAILS
(EMP_ID INT ,EMP_NAME VARCHAR(20));
---Hello---
CREATE TABLE IF NOT EXISTS 
LOGIN.CHECK1(CHECK_ID INT,CHECK_POST VARCHAR(20));
